BEGIN;

INSERT INTO public.tabibi_apps (
  title,
  short_description,
  full_description,
  price,
  billing_period,
  image_url,
  category,
  features,
  screenshots,
  component_key,
  is_active,
  color,
  preview_link,
  developer_id,
  integration_type,
  integration_target,
  icon_name,
  pricing_type,
  payment_type,
  billing_interval_unit,
  billing_interval_count,
  trial_interval_unit,
  trial_interval_count,
  currency,
  images
) VALUES
(
  'مساعد طبيبي الذكي',
  'تشخيص ذكي وتحليل بيانات',
  'مساعد شخصي متطور يعتمد على الذكاء الاصطناعي لتحليل سجلات المرضى وتقديم اقتراحات تشخيصية دقيقة.',
  200,
  'monthly',
  'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=60',
  'AI',
  '["تحليل الأعراض","تلخيص التاريخ المرضي","اقتراح خطط علاجية"]'::jsonb,
  '["https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=60","https://images.unsplash.com/photo-1576091160550-2187580023f7?w=800&auto=format&fit=crop&q=60","https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=800&auto=format&fit=crop&q=60"]'::jsonb,
  'ai_assistant',
  true,
  'text-purple-600 bg-purple-100',
  NULL,
  NULL,
  'none',
  NULL,
  'Bot',
  'paid',
  'recurring',
  'month',
  1,
  NULL,
  NULL,
  'EGP',
  '[]'::jsonb
),
(
  'Tabibi Profile',
  'صفحتك الشخصية المتكاملة على الإنترنت',
  'أنشئ موقعك الشخصي بدقائق. يعرض Tabibi Profile بياناتك، خبراتك، مواعيد عيادتك، وآراء المرضى في صفحة احترافية واحدة.',
  150,
  'monthly',
  'https://i.ibb.co/tTSnJpqB/20260110-214108-0000.png',
  'Marketing',
  '["عرض بيانات العيادة","عرض المؤهلات والشهادات","رابط حجز مباشر","معرض صور للعيادة"]'::jsonb,
  '[]'::jsonb,
  'tabibi_profile',
  true,
  'bg-primary/10',
  'https://tabibi.site/doctor-profile/REPLACE_WITH_SAMPLE',
  NULL,
  'full',
  '/doctor-profile',
  'UserCircle',
  'paid',
  'recurring',
  'month',
  1,
  NULL,
  NULL,
  'EGP',
  '["https://i.ibb.co/jvWhr2WQ/Screenshot-20260110-204518-Chrome-2.jpg","https://i.ibb.co/kssgNShx/Screenshot-20260110-204530-Chrome-2.jpg","https://i.ibb.co/PGN1fKHL/Screenshot-20260110-204532-Chrome-2.jpg"]'::jsonb
),
(
  'نظام الحجز الإلكتروني المتطور',
  'إدارة متقدمة للحجوزات تشمل الإحصائيات، الحجوزات غير المكتملة، وحظر الأرقام المزعجة.',
  'يوفر هذا التطبيق لوحة تحكم شاملة للحجز الإلكتروني. يمكنك من خلاله متابعة الحجوزات، الاطلاع على إحصائيات الزوار، متابعة الحجوزات التي لم تكتمل، بالإضافة إلى خاصية حظر الأرقام المزعجة.',
  0,
  'one_time',
  NULL,
  'Management',
  '[
    {"title":"إحصائيات متقدمة","description":"تتبع عدد الزيارات ونسب التحويل"},
    {"title":"الحجوزات غير المكتملة","description":"شاهد من بدأ الحجز ولم يكمله"},
    {"title":"نظام الحظر","description":"امنع الأرقام المزعجة من الحجز"}
  ]'::jsonb,
  '[]'::jsonb,
  'advanced_online_booking',
  true,
  'text-teal-600 bg-teal-100',
  '/online-booking',
  NULL,
  'full',
  '/online-booking',
  'Calendar',
  'free',
  'one_time',
  NULL,
  NULL,
  NULL,
  NULL,
  'EGP',
  '[]'::jsonb
),
(
  'Tabibi Affiliate',
  'إدارة روابط الإحالة والعمولات المتكررة',
  'تطبيق لإدارة برنامج التسويق بالعمولة: رابط إحالة + QR + لوحة تحكم + مستويات محفزة + عمولات شهرية متكررة طالما الطبيب مشترك.',
  0,
  'one_time',
  NULL,
  'Marketing',
  '[]'::jsonb,
  '[]'::jsonb,
  'tabibi_affiliate',
  true,
  'bg-primary/10',
  '/affiliate',
  NULL,
  'none',
  NULL,
  'Handshake',
  'free',
  'one_time',
  NULL,
  NULL,
  NULL,
  NULL,
  'EGP',
  '[]'::jsonb
),
(
  'حملات واتساب',
  'تسويق وتواصل آلي',
  'منصة متكاملة لإدارة حملاتك التسويقية عبر واتساب. تواصل مع مرضاك بفعالية.',
  150,
  'monthly',
  'https://images.unsplash.com/photo-1611746341450-953b7f282474?w=800&auto=format&fit=crop&q=60',
  'Marketing',
  '["رسائل جماعية","قوالب جاهزة","جدولة"]'::jsonb,
  '["https://images.unsplash.com/photo-1611746341450-953b7f282474?w=800&auto=format&fit=crop&q=60","https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&auto=format&fit=crop&q=60"]'::jsonb,
  'whatsapp_campaigns',
  true,
  'text-green-600 bg-green-100',
  NULL,
  NULL,
  'none',
  NULL,
  'MessageCircle',
  'paid',
  'recurring',
  'month',
  1,
  NULL,
  NULL,
  'EGP',
  '[]'::jsonb
),
(
  'التقارير المتقدمة',
  'تحليلات شاملة للعيادة',
  'لوحة تحكم تحليلية تمنحك رؤية عميقة لأداء عيادتك.',
  100,
  'monthly',
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=60',
  'Management',
  '["تحليل الإيرادات","تتبع مصادر المرضى","تصدير البيانات"]'::jsonb,
  '["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=60","https://images.unsplash.com/photo-1543286386-713df548e9cc?w=800&auto=format&fit=crop&q=60"]'::jsonb,
  'advanced_reports',
  true,
  'text-blue-600 bg-blue-100',
  NULL,
  NULL,
  'none',
  NULL,
  'BarChart3',
  'paid',
  'recurring',
  'month',
  1,
  NULL,
  NULL,
  'EGP',
  '[]'::jsonb
),
(
  'الموقع الإلكتروني',
  'واجهة احترافية لعيادتك',
  'احصل على موقع إلكتروني متكامل واحترافي لعيادتك.',
  3000,
  'yearly',
  'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=60',
  'Marketing',
  '["نطاق خاص","تصميم عصري","حجز مواعيد"]'::jsonb,
  '["https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=60","https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=60"]'::jsonb,
  'clinic_website',
  true,
  'text-indigo-600 bg-indigo-100',
  NULL,
  NULL,
  'none',
  NULL,
  'Globe',
  'paid',
  'recurring',
  'year',
  1,
  NULL,
  NULL,
  'EGP',
  '[]'::jsonb
),
(
  'التأمين الطبي',
  'إدارة مطالبات ذكية',
  'نظام ذكي لتبسيط التعامل مع شركات التأمين.',
  250,
  'monthly',
  'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&auto=format&fit=crop&q=60',
  'Management',
  '["التحقق من التغطية","إرسال المطالبات","تنبيهات النواقص"]'::jsonb,
  '["https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&auto=format&fit=crop&q=60","https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=60"]'::jsonb,
  'insurance_manager',
  true,
  'text-orange-600 bg-orange-100',
  NULL,
  NULL,
  'none',
  NULL,
  'ShieldCheck',
  'paid',
  'recurring',
  'month',
  1,
  NULL,
  NULL,
  'EGP',
  '[]'::jsonb
)
ON CONFLICT (component_key) DO UPDATE SET
  title = EXCLUDED.title,
  short_description = EXCLUDED.short_description,
  full_description = EXCLUDED.full_description,
  price = EXCLUDED.price,
  billing_period = EXCLUDED.billing_period,
  image_url = EXCLUDED.image_url,
  category = EXCLUDED.category,
  features = EXCLUDED.features,
  screenshots = EXCLUDED.screenshots,
  is_active = EXCLUDED.is_active,
  color = EXCLUDED.color,
  preview_link = EXCLUDED.preview_link,
  developer_id = EXCLUDED.developer_id,
  integration_type = EXCLUDED.integration_type,
  integration_target = EXCLUDED.integration_target,
  icon_name = EXCLUDED.icon_name,
  pricing_type = EXCLUDED.pricing_type,
  payment_type = EXCLUDED.payment_type,
  billing_interval_unit = EXCLUDED.billing_interval_unit,
  billing_interval_count = EXCLUDED.billing_interval_count,
  trial_interval_unit = EXCLUDED.trial_interval_unit,
  trial_interval_count = EXCLUDED.trial_interval_count,
  currency = EXCLUDED.currency,
  images = EXCLUDED.images;

COMMIT;

